package com.mtm.ksu.mobile.common;

public class Constants {
	/*Preferences key*/
	public static String ANDROMEDA_MOBILE_KSU_PREFERENCES = "ANDROMEDA_MOBILE_KSU_PREFERENCES";
	
	/*Action Root*/;
	public static String ANDROMEDA_ACTION_ROOT = "index.php/";
	public static String HTTP_SERVER_SERVICE = "http://10.0.2.2:80/mobileservis/";
	//public static String HTTP_SERVER_SERVICE = "http://192.168.10.11/AndromedaService/";
	
	/*Printer Name*/
	public static String ANDROMEDA_BLUETOOTH_PRINTER_NAME = "AB-320M";
	
	/*Konfigurasi Local Db*/
	public static String ANDROMEDA_LOCAL_ADMIN_USER = "ADMIN";
	public static String ANDROMEDA_KEYNAME_LOCAL_ADMIN_PASSWORD = "ANDROMEDA_LOCAL_ADMIN_PASSWORD";
	public static String ANDROMEDA_KEYNAME_SERVER_ADDRESS = "ANDROMEDA_SERVER_ADDRESS";
	public static String ANDROMEDA_KEYNAME_BLUETOOTH_PRINTER = "ANDROMEDA_BLUETOOTH_PRINTER_NAME";
	public static String ANDROMEDA_KEYNAME_KODETRANSSETOR= "ANDROMEDA_SERVER_KODETRANSSETOR";
	public static String ANDROMEDA_KEYNAME_KODETRANSTARIK = "ANDROMEDA_SERVER_KODETRANSTARIK";
	public static String ANDROMEDA_KEYNAME_KODETRANSANGSURAN = "ANDROMEDA_SERVER_KODETRANSANGSURAN";
	public static String ANDROMEDA_KEYNAME_COMPANY_NAME = "ANDROMEDA_COMPANY_NAME";
	
		
	/*SERVER RESPONSE TYPES*/
	public static String SERVER_SUCCESS_RESPONSE = "SUCCESS";
	public static String SERVER_INVALID_RESPONSE = "INVALID";
	public static String SERVER_FAIL_RESPONSE = "FAIL";
	public static String SERVER_ERROR_RESPONSE = "ERROR";
	public static String SERVER_EMPTY_RESPONSE = "EMPTY";
	
	/*PRINTING INFO*/
	public static String PRINTING_TRANS_TYPE_SETOR_TABUNGAN = "SETOR_TABUNGAN";
	public static String PRINTING_TRANS_TYPE_TARIK_TABUNGAN = "TARIK_TABUNGAN";
	public static String PRINTING_TRANS_TYPE_ANGSURAN = "ANGSURAN";
	
}
